name: Label requires reviews - BlueWeabo Fork
author: BlueWeabo <ilia.iliev2005@gmail.com> previous - TravelPerk <engineering@travelperk.com>
description: This Github action will require a minimum number of reviews if a label is present.
runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  github_token:
    description: 'Github token to authenticate Octokit'
    required: true
  rules_yaml:
    description: 'Labels for which to add more reviews required for it.'
    required: true
branding:
  icon: 'user-check'  
  color: 'green'

